sudo: required

services:
 - docker

language: python

before_install:
 - sudo apt-get update
 - git checkout feature/add-travisci
 - git clone https://github.com/jnkrupp/dcc-action-service.git
# - docker-compose -f docker-compose.yml up --build -d
# - docker-compose -f docker-compose.yml down
# - docker-compose help
script:
 - cd dcc-action-service
# - docker build -t justin_action_service_image -f Dockerfile_decider .
 - sudo docker-compose -f docker-compose.yml up --build -d
 - sudo docker-compose -f docker-compose.yml down

