sudo: required

services:
 - docker

language: python

before_install:
 - git clone https://github.com/jnkrupp/dcc-action-service.git

script:
 - cd dcc-action-service
 - cd luigi_task_executor
 - docker build -t justin_action_service_image -f Dockerfile_decider .
 - docker-compose up --build -d
 - docker-compose down
